export const GET_EMPLOYEES_REQUESTED = 'GET_EMPLOYEES_REQUESTED';
export const GET_EMPLOYEES_SUCCESS = 'GET_EMPLOYEES_SUCCESS';
export const ADD_EMPLOYEES_REQUESTED = 'ADD_EMPLOYEES_REQUESTED';
export const ADD_EMPLOYEES_SUCCESS = 'ADD_EMPLOYEES_SUCCESS';
export const DELETE_EMPLOYEES_REQUESTED = 'DELETE_EMPLOYEES_REQUESTED';
export const DELETE_EMPLOYEES_SUCCESS = 'DELETE_EMPLOYEES_SUCCESS';
export const EMPLOYEES_FAILED = 'EMPLOYEES_FAILED';